language: node_js

node_js:
  - "0.12"
  - "4.2"
  - "5.9"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - 'npm install -g npm@3'

script:
  - npm --version
  - npm run check-ci

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - npm run build
  - cat coverage/client/*/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
